"""
Constants for training and model configuration.
"""

DEFAULT_BATCH_SIZE = 64
DEFAULT_LEARNING_RATE = 1e-3
DEFAULT_WEIGHT_DECAY = 0.0
DEFAULT_EPOCHS = 10
DEFAULT_NUM_WORKERS = 4
DEFAULT_PREFETCH_FACTOR = 4
